//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoSAMAGO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculo
    {
        public int IdVeiculo { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public decimal Valor { get; set; }
        public string AnoModelo { get; set; }
        public int AnoFabricacao { get; set; }
        public int Quilometragem { get; set; }
        public string FinalPlaca { get; set; }
        public int CorID { get; set; }
        public int CombustivelID { get; set; }
        public int CambioID { get; set; }
        public int MarcaID { get; set; }
    
        public virtual Cambio Cambio { get; set; }
        public virtual Combustivel Combustivel { get; set; }
        public virtual Cor Cor { get; set; }
        public virtual Marca Marca { get; set; }
    }
}
